#!/bin/bash
# run_poisonedrag_victims.sh — PoisonedRAG baseline on the MAIN-TABLE victims.
#
# Poison texts are fixed (generated by qwen3-8b, baseline/poisonedrag/
# gen_poison_writes.py). This script evaluates them against each victim in the
# main table (xlam-2-8b / qwen3-8b / gpt-oss-20b / llama-3.1-8b), one per row,
# same protocol as the cluster main table: inject once, then eval-after per
# victim using that victim's own clean baseline.
#
# The inject phase is idempotent-guarded by a marker file; the KB must start
# clean (no poison) so the first inject writes exactly the 300 chunks.
set -u
ROOT=/mnt/disk/cwh/AgenticRAG
PY=/home/cwh/anaconda3/envs/agents/bin/python
VLLM=/home/cwh/anaconda3/envs/agents/bin/vllm
LOG=$ROOT/results/logs
mkdir -p "$LOG"
export PYTHONUNBUFFERED=1
export AGENTIC_RAG_ASK_WORKERS=8
export AGENTIC_RAG_BASE_URL=http://localhost:8000/v1
POISON_JSON=$ROOT/results/baseline_poisonedrag_60.json
TARGET_REC=$ROOT/results/baseline_poisonedrag_targets.json
INJECT_MARKER=$ROOT/results/baseline_poisonedrag_injected.flag
VICTIMS=(qwen3-8b gpt-oss-20b llama-3.1-8b)   # xlam-2-8b already done (flip 14/27)

declare -A SPECS=(
  [xlam-2-8b]="/mnt/disk/cwh/LLMs/xlam-2-8b-fc-r|xlam-2-8b|xlam|--max-model-len 16384 --chat-template /mnt/disk/cwh/LLMs/xlam_chat_template.jinja"
  [qwen3-8b]="/mnt/disk/cwh/LLMs/Qwen3-8B|qwen3-8b|hermes|--max-model-len 16384 --reasoning-parser qwen3"
  [gpt-oss-20b]="/mnt/disk/cwh/LLMs/gpt-oss-20b|gpt-oss-20b|openai|--max-num-seqs 64 --max-model-len 32768"
  [llama-3.1-8b]="/mnt/disk/cwh/LLMs/Meta-Llama-3.1-8B-Instruct|llama-3.1-8b|llama3_json|--max-model-len 16384 --chat-template /mnt/disk/cwh/LLMs/Meta-Llama-3.1-8B-Instruct/chat_template_multitool.jinja"
)

serve_victim () {  # $1 victim name
  local vpath vname vparser vextra
  IFS='|' read -r vpath vname vparser vextra <<< "${SPECS[$1]}"
  pkill -f "vllm serve" 2>/dev/null
  pkill -f "VLLM::EngineCore" 2>/dev/null
  sleep 8
  for _ in $(seq 1 60); do
    used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits)
    [ "${used:-99999}" -lt 2000 ] && break
    sleep 5
  done
  nohup "$PY" "$VLLM" serve "$vpath" --port 8000 \
      --gpu-memory-utilization 0.85 \
      --served-model-name "$vname" --enable-auto-tool-choice --tool-call-parser "$vparser" $vextra \
      > "$LOG/vllm_$vname.log" 2>&1 &
  for _ in $(seq 1 150); do
    curl -s --max-time 3 "http://localhost:8000/v1/models" 2>/dev/null | grep -q "\"id\": *\"$vname\"" && return 0
    sleep 5
  done
  echo "FAILED to serve $vname" >&2; return 1
}

# build target records once (60 shared HotpotQA targets)
if [ ! -f "$TARGET_REC" ]; then
  ( cd "$ROOT/experiments" && "$PY" - <<'EOF'
import json, sys
src = json.load(open("../data/targets/hotpotqa.json"))
recs = {q: {"question": r["question"], "gold": r["correct answer"], "wrong": r["incorrect answer"]}
        for q, r in src.items()}
json.dump(recs, open("../results/baseline_poisonedrag_targets.json", "w"), ensure_ascii=False)
print("target records written:", len(recs))
EOF
  )
fi

# inject once (guarded)
if [ ! -f "$INJECT_MARKER" ]; then
  echo "=== clean KB poison leftovers ==="
  ( cd "$ROOT/experiments" && "$PY" -c "
import sys, yaml
sys.path.insert(0, '../src')
from agentic_rag.kb.store import KnowledgeStore
cfg = yaml.safe_load(open('../configs/default.yaml'))
s = KnowledgeStore(persist_dir=cfg['kb']['persist_dir'], collection=cfg['kb']['collection'], model_path=cfg['embedding']['model_path'], dim=cfg['embedding']['dim'])
import chromadb
client = chromadb.PersistentClient(path=cfg['kb']['persist_dir'])
coll = client.get_collection(cfg['kb']['collection'])
ids = coll.get(where={'is_poison': 1})['ids']
if ids:
    coll.delete(ids=ids)
    print('cleaned', len(ids), 'poison')
else:
    print('KB already clean')
" )
  echo "=== inject PoisonedRAG poison (300 chunks) ==="
  ( cd "$ROOT/experiments" && AGENTIC_RAG_RUN_ID=baseline_pr_main "$PY" longtail_attack.py \
      --phase inject-from --inject-from "$POISON_JSON" --results-name baseline_pr_main_inj 2>&1 | tail -2 )
  touch "$INJECT_MARKER"
fi

for V in "${VICTIMS[@]}"; do
  OUT="$ROOT/results/baseline_poisonedrag_eval_${V}.json"
  if [ -s "$OUT" ]; then
    echo "=== skip $V (already done) ==="
    continue
  fi
  echo "=== serve victim $V ==="
  serve_victim "$V" || { echo "serve failed for $V"; continue; }
  echo "=== eval-after: $V ==="
  ENV_EXTRA=""
  if [ "$V" = "qwen3-8b" ]; then
    export AGENTIC_RAG_CHAT_KWARGS='{"enable_thinking": false}'
  else
    unset AGENTIC_RAG_CHAT_KWARGS
  fi
  ( cd "$ROOT/experiments" && AGENTIC_RAG_RUN_ID="baseline_pr_main_${V}" \
      "$PY" longtail_attack.py --phase eval-after --model "$V" \
      --target-records "$TARGET_REC" --results-name "baseline_poisonedrag_eval_${V}" 2>&1 | tail -2 )
  echo "=== done $V ==="
done

echo "=== all victims done ==="