#!/bin/bash
# run_poisonedrag_musique_victims.sh — PoisonedRAG baseline on MuSiQue.
#
# Poison texts are fixed (generated by qwen3-8b from the frozen 59 MuSiQue
# targets). Evaluated against each main-table victim on the MuSiQue KB
# (data/chroma_musique, collection musique_kb). Same protocol as the cluster
# main-table MuSiQue rows.
set -u
ROOT=/mnt/disk/cwh/AgenticRAG
PY=/home/cwh/anaconda3/envs/agents/bin/python
VLLM=/home/cwh/anaconda3/envs/agents/bin/vllm
LOG=$ROOT/results/logs
mkdir -p "$LOG"
export PYTHONUNBUFFERED=1
export AGENTIC_RAG_ASK_WORKERS=8
export AGENTIC_RAG_BASE_URL=http://localhost:8000/v1
POISON_JSON=$ROOT/results/baseline_poisonedrag_musique.json
TARGET_REC=$ROOT/results/baseline_poisonedrag_musique_targets.json
INJECT_MARKER=$ROOT/results/baseline_poisonedrag_musique_injected.flag
KB_DIR=$ROOT/data/chroma_musique
KB_COLL=musique_kb
VICTIMS=(xlam-2-8b qwen3-8b gpt-oss-20b llama-3.1-8b)

declare -A SPECS=(
  [xlam-2-8b]="/mnt/disk/cwh/LLMs/xlam-2-8b-fc-r|xlam-2-8b|xlam|--max-model-len 16384 --chat-template /mnt/disk/cwh/LLMs/xlam_chat_template.jinja"
  [qwen3-8b]="/mnt/disk/cwh/LLMs/Qwen3-8B|qwen3-8b|hermes|--max-model-len 16384 --reasoning-parser qwen3"
  [gpt-oss-20b]="/mnt/disk/cwh/LLMs/gpt-oss-20b|gpt-oss-20b|openai|--max-num-seqs 64 --max-model-len 32768"
  [llama-3.1-8b]="/mnt/disk/cwh/LLMs/Meta-Llama-3.1-8B-Instruct|llama-3.1-8b|llama3_json|--max-model-len 16384 --chat-template /mnt/disk/cwh/LLMs/Meta-Llama-3.1-8B-Instruct/chat_template_multitool.jinja"
)

serve_victim () {  # $1 victim name
  local vpath vname vparser vextra
  IFS='|' read -r vpath vname vparser vextra <<< "${SPECS[$1]}"
  pkill -f "vllm serve" 2>/dev/null
  pkill -f "VLLM::EngineCore" 2>/dev/null
  sleep 8
  for _ in $(seq 1 60); do
    used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits)
    [ "${used:-99999}" -lt 2000 ] && break
    sleep 5
  done
  nohup "$PY" "$VLLM" serve "$vpath" --port 8000 \
      --gpu-memory-utilization 0.85 \
      --served-model-name "$vname" --enable-auto-tool-choice --tool-call-parser "$vparser" $vextra \
      > "$LOG/vllm_$vname.log" 2>&1 &
  for _ in $(seq 1 150); do
    curl -s --max-time 3 "http://localhost:8000/v1/models" 2>/dev/null | grep -q "\"id\": *\"$vname\"" && return 0
    sleep 5
  done
  echo "FAILED to serve $vname" >&2; return 1
}

# build target records once (59 frozen MuSiQue targets)
if [ ! -f "$TARGET_REC" ]; then
  ( cd "$ROOT/experiments" && "$PY" - <<'EOF'
import json, sys
src = json.load(open("../research/frozen/musique_targets_59.json"))
recs = {q: {"question": r["question"], "gold": r["gold"], "wrong": r["wrong"]}
        for q, r in src.items()}
json.dump(recs, open("../results/baseline_poisonedrag_musique_targets.json", "w"), ensure_ascii=False)
print("target records written:", len(recs))
EOF
  )
fi

# inject once (guarded)
if [ ! -f "$INJECT_MARKER" ]; then
  echo "=== clean musique KB poison leftovers ==="
  ( cd "$ROOT/experiments" && "$PY" -c "
import sys, yaml
sys.path.insert(0, '../src')
import chromadb
client = chromadb.PersistentClient(path='$KB_DIR')
coll = client.get_collection('$KB_COLL')
ids = coll.get(where={'is_poison': 1})['ids']
if ids:
    coll.delete(ids=ids)
    print('cleaned', len(ids), 'poison')
else:
    print('KB already clean')
" )
  echo "=== inject PoisonedRAG poison (295 chunks) into musique KB ==="
  ( cd "$ROOT/experiments" && AGENTIC_RAG_RUN_ID=baseline_pr_mus_main "$PY" longtail_attack.py \
      --phase inject-from --inject-from "$POISON_JSON" \
      --kb-dir "$KB_DIR" --kb-collection "$KB_COLL" \
      --results-name baseline_pr_mus_inj 2>&1 | tail -2 )
  touch "$INJECT_MARKER"
fi

for V in "${VICTIMS[@]}"; do
  OUT="$ROOT/results/baseline_poisonedrag_musique_eval_${V}.json"
  if [ -s "$OUT" ]; then
    echo "=== skip $V (already done) ==="
    continue
  fi
  echo "=== serve victim $V ==="
  serve_victim "$V" || { echo "serve failed for $V"; continue; }
  echo "=== eval-after: $V ==="
  ENV_EXTRA=""
  if [ "$V" = "qwen3-8b" ]; then
    export AGENTIC_RAG_CHAT_KWARGS='{"enable_thinking": false}'
  else
    unset AGENTIC_RAG_CHAT_KWARGS
  fi
  ( cd "$ROOT/experiments" && AGENTIC_RAG_RUN_ID="baseline_pr_mus_${V}" \
      "$PY" longtail_attack.py --phase eval-after --model "$V" \
      --target-records "$TARGET_REC" --kb-dir "$KB_DIR" --kb-collection "$KB_COLL" \
      --results-name "baseline_poisonedrag_musique_eval_${V}" 2>&1 | tail -2 )
  echo "=== done $V ==="
done

echo "=== all victims done ==="